# Generated by Django 3.1.7 on 2021-05-06 10:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('doctors', models.CharField(max_length=100)),
                ('hospital_image', models.ImageField(upload_to='pics/')),
                ('hospital_address', models.CharField(max_length=100)),
                ('hospital_contactinfo', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('hospital_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.place')),
                ('hospital_sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
